### ISSUE TITLE
When on click results does not disappear

### ISSUE THREAD

**Issue by DiegoGallegos4** [l-urence/react-native-autocomplete-input#19]
Whenever you search a result and click that result, the list query component does not go away. If you don't click any other input, it wont go away.  Is there any solution to this?

An example of the behavior: 
![image](https://cloud.githubusercontent.com/assets/5933437/18573512/52acf3be-7b81-11e6-91f9-f9b59fa6746c.png)

Im using RN 0.33.0
RN autocomplete 2.0.0-rc.0

**Comment by l-urence** [comment]
@DiegoGallegos4 are you running on Android or iOS?

**Comment by DiegoGallegos4** [comment]
on IOS. Ill test this week on Android.

**Comment by cyclomaticsegal** [comment]
@l-urence  I experience the same issue on Android... selection populates textbox but does not close the selection list.

**Comment by qlerebours** [comment]
It's not working for me on Android. When I click, it changes the textfield with the content I clicked, but it's not hidding the list.

**Comment by qlerebours** [comment]
The problem is: 
`data={films.length === 1 && comp(query, films[0].title) ? [] : films}`
Because if the title of the film is a part of the title of another film then films.length != 1.
For example, I'm using the Autocomplete component to load a list of cities, and when I click on "Paris", it changes the query to "Paris". The problem is that there are cities called Villeparisis or Parisot.
I wrote a solution with a "clicked" variable in the state:
`this.state = {
            query: '',
            films: [],
            clicked : false
 };`

Autocomplete data attribute is: 
` data={((films.length === 1 && comp(query, films[0])) || this.state.clicked) ? [] : films}`

OnChangeText attribute is:
`onChangeText={function(text) {
      self.setState({ query: text });
      self.setState({ clicked: false });
}}`

and finally:
`<TouchableOpacity onPress={function() {
      self.setState({query: data});
      self.setState({clicked: true});
}}>
      <Text>{data}</Text>
</TouchableOpacity>`

**Comment by l-urence** [comment]
@qlerebours thx for charing your approach! Yes, the code from the example is just a simple illustration how the autocomplete could be used.

It's up to the application to open and close the suggestion list by passing a list with items or an empty list. This is because the filtering is hard to generalise for every application and most times done server side. (just for clarification)

**Comment by qlerebours** [comment]
@l-urence you're totally right and i'd like to thank you for you great job !
I hope my answer will be able to help @DiegoGallegos4

**Comment by DiegoGallegos4** [comment]
@qlerebours Works like a charm mate!
